### ISSUE TITLE
ros-hydro-rosconsole fails to build on Mavericks

### ISSUE THREAD

**Issue by fferri** [kyonifer/ros-macports#6]
Scanning dependencies of target rosconsole
[100%] Building CXX object CMakeFiles/rosconsole.dir/src/rosconsole/rosconsole.cpp.o
Linking CXX shared library ../../devel_isolated/rosconsole/lib/librosconsole.dylib
Undefined symbols for architecture x86_64:
  "log4cxx::AppenderSkeleton::setOption(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      vtable for ros::console::ROSConsoleStdioAppender in rosconsole.cpp.o
      construction vtable for log4cxx::AppenderSkeleton-in-ros::console::ROSConsoleStdioAppender in rosconsole.cpp.o
  "log4cxx::File::File(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      ros::console::do_initialize() in rosconsole.cpp.o
  "log4cxx::Logger::getLogger(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      ros::console::initializeLogLocation(ros::console::LogLocation_, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, ros::console::levels::Level) in rosconsole.cpp.o
  "log4cxx::Logger::forcedLog(log4cxx::helpers::ObjectPtrTlog4cxx::Level const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, log4cxx::spi::LocationInfo const&) const", referenced from:
      ros::console::print(ros::console::FilterBase_, log4cxx::Logger_, ros::console::levels::Level, char const_, int, char const_, char const_, ...) in rosconsole.cpp.o
      ros::console::print(ros::console::FilterBase_, log4cxx::Logger_, ros::console::levels::Level, std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const_, int, char const_) in rosconsole.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [../../devel_isolated/rosconsole/lib/librosconsole.dylib] Error 1
make[1]: **\* [CMakeFiles/rosconsole.dir/all] Error 2
make: **\* [all] Error 2

$ uname -srm
Darwin 13.0.0 x86_64

$ xcodebuild -version
Xcode 5.0.1
Build version 5A2053

$ clang --version
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.0.0
Thread model: posix

**Comment by fferri** [comment]
this one fails both with clang and with gcc-4.8

**Comment by venabled** [comment]
I still haven't been able to resolve this. On your error above did you use gcc4-8 or clang? Either one I'm using is giving me different linking errors that I haven't been able to resolve.

**Comment by venabled** [comment]
For example, I've gotten complaints about not finding functions from boost, log4cxx, and rostime (which are all libraries either explicitly called out by find_package() in cmake, or from find_package(catkin COMPONENTS ___ ) in the CMakeLists.txt. 

Also there's some conditional statements in the CMakeLists.txt for rosconsole that tries to build with gcc-4.2 on mac, maybe I should try calling that out in the compiler 

I wonder if @wjwwood has any insight.

**Comment by venabled** [comment]
https://code.ros.org/trac/ros/ticket/3626

**Comment by wjwwood** [comment]
http://answers.ros.org/question/95056/building-rosconsole-osx-109/

**Comment by wjwwood** [comment]
I haven't had time to look into it.

**Comment by venabled** [comment]
According to both @fferri and myself this now builds on 10.9. Should test with @kyonifer to make sure it's not broken on ML still.

**Comment by kyonifer** [comment]
Going to make the call that most people have switched to Mavericks given the free release, so we'll focus on supporting that unless someone has a specific problem.

**Comment by ghost** [comment]
Hello,

I'm trying to install ROS Hydro on Lion and the installation fails during the building of ros-hydro-rosconsole. 

I can't update my Macbook to a newer OS because it's too old (2008). 

I put the build log [here](http://pastebin.com/U7RjQy7G), I hope someone will find a fix for that issue

**Comment by venabled** [comment]
Hmm, it says it in there.. 

:info:build [100%] Building CXX object CMakeFiles/rosconsole.dir/src/rosconsole/rosconsole.cpp.o
:info:build /opt/local/var/macports/build/_Users_blackswords_ros-macports_hydro_ros-hydro-rosconsole/ros-hydro-rosconsole/work/ros_comm-release-release-hydro-rosconsole-1.9.50-0/src/rosconsole/rosconsole.cpp:33:2: error: #error This code is known to provoke a compiler crash with llvm-gcc 4.2. You will have better luck with clang++. See code.ros.org/trac/ros/ticket/3626

Looks like you're using llvm-gcc 4.2, and we're all tested on clang. You could try to do a "search all and replace" in your ros-macports directory to try to use clang. Try reading on here: 

https://trac.macports.org/wiki/UsingTheRightCompiler

Honestly I don't think we can go back and support much past Mavericks, but good luck.

**Comment by ghost** [comment]
Thanks for your answer, it helped me to find a solution. In fact, I had to comment the line 32 of rosconsole.cpp because even when specifying a clang compiler to macport, the error appears (I tried with configure.compiler=clang and configure.compiler=macports-clang-3.5, same results)

I had an other issue with roscpp, I had to apply [this](http://boost.2283326.n4.nabble.com/config-clang-int128-support-td4653826.html) solution to the boost library I installed with macport to get rid of some errors. 

After that, everything went fine. Thanks again for the support

**Comment by venabled** [comment]
Awesome, hopefully it's building and running successfully then?

**Comment by kyonifer** [comment]
If there's a patch that will allow this to work on all OSes we can definitely merge it in.
